FROM debian:latest as tini
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

FROM gcr.io/distroless/java:11
COPY --from=tini /tini* /
COPY ./target/oom-demo-0.0.1-SNAPSHOT.jar /app

EXPOSE 8888 8888

ENTRYPOINT ["/tini", "--", "java", "-jar", "/app/oom-demo-0.0.1-SNAPSHOT.jar"]
