FROM debian:latest as tini
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

FROM gcr.io/distroless/java:11
COPY --from=tini /tini* /
COPY ./target/oom-demo-0.0.1-SNAPSHOT.jar /app


ENV SERVER_PORT 8888
ENV DB_ADDRESS jdbc:postgresql://pre-dev-backend-db.cfu2xhpbzyk4.us-east-1.rds.amazonaws.com:5432/postgres
ENV DB_USER postgres
ENV DB_PASSWORD postgres



EXPOSE 8888 8888

ENTRYPOINT ["/tini", "--", "java", "-jar", "/app/oom-demo-0.0.1-SNAPSHOT.jar"]
