# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
 
    - name: Build mvn project and container
      run: |
          docker build -t oom-demo:${{ github.sha }} .
          
    - name: Minify docker image with docker-slim
      run: |
       curl -LO https://downloads.dockerslim.com/releases/1.32.0/dist_linux.tar.gz
       tar -xzf dist_linux.tar.gz
       chmod +x dist_linux 
       ./dist_linux/docker-slim build --http-probe=false --target oom-demo:${{ github.sha }}
       
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
          image-ref: 'oom-demo:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'

    - name: Upload Trivy Scan Resulte to GitHub SecTab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'
   
      
      
